### PR TITLE
Fix #245: Refactor RestRequestBuilderGenerator to accept arg file wit…

### LINKED ISSUE #245: Gradle task generateMainDataTemplate can fail with "error=7, Argument list too long"
Task `generateMainDataTemplate` can fail when asked to process a large amount of schema files, as those files are passed by `` directly to the CLI as an array.

I will refactor `RestRequestBuilderGenerator` and `GenerateRestClientTask` to allow for this possibility.

### PR DESCRIPTION
**Pull request by DPUkyle**
…h '@' syntax

 - Also add test coverage for psvm method

Gradle task refactor is still pending, but this gives @evanw555 a chance to start reviewing.

### CODE REVIEW

File: restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java [hunk 1]
```diff
@@ -0,0 +1,141 @@
+package com.linkedin.restli.tools.clientgen;
```
Comment (evanw555) [inline restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java]: Add license

File: restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java [hunk 2]
```diff
@@ -0,0 +1,141 @@
...
+import org.testng.annotations.Test;
+
+import java.io.BufferedReader;
+import java.io.File;
+import java.io.FileReader;
+import java.io.IOException;
+import java.nio.file.Files;
+import java.util.Collections;
+
+public class TestRestRequestBuilderGeneratorEntryPoint {
```
Comment (evanw555) [inline restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java]: Is this basically just a copy of the existing test, but using PSVM instead? Would it be possible to keep this in the existing test class, or would that be too messy you think?

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java [hunk 3]
```diff
@@ -51,8 +51,8 @@
  */
 public class RestRequestBuilderGenerator
 {
-  private static final String GENERATOR_REST_GENERATE_DATATEMPLATES = "generator.rest.generate.datatemplates";
-  private static final String GENERATOR_REST_GENERATE_VERSION = "generator.rest.generate.version";
+  protected static final String GENERATOR_REST_GENERATE_DATATEMPLATES = "generator.rest.generate.datatemplates";
+  protected static final String GENERATOR_REST_GENERATE_VERSION = "generator.rest.generate.version";
```
Comment (evanw555) [inline restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java]: Can just be package-private, right?

File: gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java [hunk 4]
```diff
@@ -156,11 +168,26 @@ public void generate()
...
+        javaExecSpec.args(sources);
       }).assertNormalExitValue()
     );
   }
 
+  /**
+   * Helper method to generate an argument file, containing one input file per line.
+   * This should be prefixed with '@' and passed to the final argument of RestRequestBuilderGenerator.
+   */
+  private File createArgFile(String prefix, List<String> files) {
```
Comment (evanw555) [inline gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java]: Although this logic is quite simple, it would probably be worthwhile to refactor this into its own utility class within `:gradle-plugins`, something like `ArgumentFileBuilder` (I say "___Builder" to stress that static utilities are unmaintainable) which handles creating the temp file and returning its "ID" (e.g. `@/something/something`). I think this would be a simple refactoring and would allow us to easily reuse it later, plus it removes complexity from this class.

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java [hunk 5]
```diff
@@ -51,8 +51,8 @@
  */
```
Comment (evanw555) [inline restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java]: Can you add a `TODO` here which says that we want to refactor this tool into a nicer CLI app using Commons-CLI?

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java [hunk 6]
```diff
@@ -64,10 +64,19 @@
   public static void main(String[] args)
       throws IOException
   {
+    String[] sources = new String[0];
+
     if (args.length < 2)
     {
       _log.error("Usage: RestRequestBuilderGenerator targetDirectoryPath [sourceFile or sourceDirectory]+");
       System.exit(1);
+    } else if (args.length == 2 && args[1].startsWith("@")) {
```
Comment (evanw555) [inline restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java]: Similar comment as the one above, there should be a utility class within `:restli-tools` which handles the parsing side of things. Although this logic here isn't too complicated, this will proactively keep this sort of stuff from exploding if we need to extend or reuse it, plus it keeps this class clean.

File: restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java (hunk 2 above)
Comment (DPUkyle) [reply restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java]: Due to the messiness of the sysprop backup/restore, I chose to extract it to a separate class. I'm still worried about parallelism or unwanted side-effects of this, so we should kill this.

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java (hunk 3 above)
Comment (DPUkyle) [reply restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java]: Yes, I'll try with default access.

File: restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java (hunk 1 above)
Comment (DPUkyle) [reply restli-tools/src/test/java/com/linkedin/restli/tools/clientgen/TestRestRequestBuilderGeneratorEntryPoint.java]: Will do.

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java (hunk 3 above)
Comment (DPUkyle) [reply restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java]: Default access works.

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java (hunk 6 above)
Comment (DPUkyle) [reply restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java]: Added class `ArgumentFileProcessor`

File: restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java (hunk 5 above)
Comment (DPUkyle) [reply restli-tools/src/main/java/com/linkedin/restli/tools/clientgen/RestRequestBuilderGenerator.java:51]: Done.

File: gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java (hunk 4 above)
Comment (DPUkyle) [reply gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/tasks/GenerateRestClientTask.java]: Added class `ArgumentFileGenerator`. Note that it can't live in `restli-tools` as `pegasus-plugins` has no dependency on it.

File: gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java [hunk 7]
```diff
@@ -0,0 +1,64 @@
...
+    // prevent instantiation
+  }
+
+  /**
+   *  Helper method to generate an argument file, containing one input file per line.
+   *  This should be later prefixed with '@' and passed to the final argument of RestRequestBuilderGenerator.
+   *
+   * @param prefix unique value to prepend to the arg file name
+   * @param files the iterable to write to an arg file, one line per entry
+   * @param tempDir the directory to hold the file (If invoked from Gradle, use org.gradle.api.Task#getTemporaryDir()
```
[the remark this answers is not in the document]
Comment (DPUkyle) [reply gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java:40]: Yes I did it this way to use as few Gradle APIs as possible; if we use `Task#getTempoaryDir()` as default storage for the arg File, the caller would have to pass a reference to the `Task` object, which is kind of icky too. Let's leave it as-is.

File: gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java [hunk 8]
```diff
@@ -0,0 +1,64 @@
...
+   * @return argument file which can be passed to a CLI or other JavaExec task
+   */
+  public static File createArgFile(String prefix, List<String> files, File tempDir)
```
[the remark this answers is not in the document]
Comment (DPUkyle) [reply gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java:43]: Fair enough - although I don't intend this to become the "restli standard". We need to stop passing arguments via sysprops on the CLI, and use a proper framework like jcommander. I'm OK with commons-cli too _if_ it can support the argfile syntax. Otherwise I strongly recommend jcommander.

File: gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (evanw555) [reply gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java]: Now I get it, makes sense.

File: gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (evanw555) [reply gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java]: Ah, I see. So for now, this will hold us over, and we'll potentially have to use it if we run into the same issue for another task in the near future. The long-term vision will be to migrate all our tools to C-CLI or JCommander.

[the remark this answers is not in the document]
Comment (DPUkyle) [reply gradle-plugins/src/main/java/com/linkedin/pegasus/gradle/internal/ArgumentFileGenerator.java]: 👍

File: generator-test/build.gradle [hunk 9]
```diff
@@ -12,7 +12,7 @@ project.idea.module.testSourceDirs.add('src/test/javaPegasus')
 apply from: "${buildScriptDirPath}/dataTemplate.gradle"
 apply from: "${buildScriptDirPath}/avroSchema.gradle"
 
-// generate pdsc files under "unionPegasus" directory with explicit ordering
+// generate pdsc args under "unionPegasus" directory with explicit ordering
```
Comment (DPUkyle) [inline generator-test/build.gradle:15]: Oh no - IntelliJ refactor got a bit too creative. Let me undo this change.

Comment (DPUkyle) [reply generator-test/build.gradle]: Fixed.
